version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'

  backend:
    build:
      context: ./backend
    env_file:
      - .env
      - ./backend/.env
    ports:
      - '${BACKEND_PORT}:3001'
    depends_on:
      - postgres
      - redis
    command: sh -c "npm run drizzle:push && npm run start"

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
      - ./frontend/.env
    ports:
      - '${FRONTEND_PORT}:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
